<main>
    <div class="container-fluid">
        <h1 class="my-1 panel-title">Dashboard SAIC</h1>
        <hr><br>                       
        <div class="seleciona-coop border border-muted rounded  mb-4">                            
            <div class="col align-self-start  align-self-center">                            
                <form class="mx-3">
                    <div class="form-group row" data-style="btn-info">
                        <label class="col-sm-4 col-form-label">Selecione uma Cooperativa e o item:</label>
                        <div class="col-sm-3">
                            <select name="coop" class="form-control-plaintext" id="coop" >
                                <option disabled selected value>Cooperativa</option>
                                <option class="text-secondary" value="1003">Geral</option>
                                <option class="text-secondary" value="3456">3456</option>
                                <option class="text-secondary" value="3210">3210</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <select name="item" class="form-control-plaintext" id="item" >
                                <option disabled selected value>Item</option>
                                <option class="text-secondary" value="coop">Cooperativa</option>
                                <option class="text-secondary" value="pa">Ponto de Atendimento</option>
                                <option class="text-secondary" value="servidores">Servidores</option>
                                <option class="text-secondary" value="dominio">Domínio</option>
                                <option class="text-secondary" value="dhcp">DHCP</option>
                                <option class="text-secondary" value="wsus">Serviço de WSUS</option>
                                <option class="text-secondary" value="backup">Política de Backup</option>
                                <option class="text-secondary" value="antivirus">Antivírus</option>
                                <option class="text-secondary" value="cfs">WEB Content Fintering</option>
                                <option class="text-secondary" value="aplicacoes">Aplicaçãoes</option>
                                <option class="text-secondary" value="visita">Visita</option>
                                <option class="text-secondary" value="relatorio">Relatório de Avaliação</option>
                            </select>
                        </div>
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-primary mb-2">Selecionar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>