<div class="container-fluid">
	<div class="row justify-content-center">

	    <div class="col-5">

	    	<form action="/autenticar" method="post" class="form-container">
			  	<div class="form-group">
			    	<label for="login">Login</label>
			    	<input type="email" class="form-control" id="login" aria-describedby="emailHelp" placeholder="Email">
			    </div>
			 	<div class="form-group">
			   		<label for="senha">Senha</label>
			    	<input type="password" class="form-control" id="senha" placeholder="Senha">
			  	</div>
			    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
				
				<?php if($this->view->login == 'erro') { ?>

	                <small class="form-text text-danger">
	                    Login ou senha incorretos.
	                </small>

	            <?php } ?>

			</form>

	    </div>

  	</div>
</div>