<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 36rem;">
      <div class="card-body">
<!--<div class="container-fluid">-->
		<div class="row">

		    <div class="col">

		    	<form action="/authenticate" method="post" class="form-container">
				  	<div class="form-group">
				    	<label for="login">Login</label>
				    	<input type="text" class="form-control" id="login" name="login" aria-describedby="emailHelp" placeholder="Login">
				    </div>
				 	<div class="form-group">
				   		<label for="senha">Senha</label>
				    	<input type="password" class="form-control" id="senha" name="senha" placeholder="Senha">
				  	</div>
				    <button type="submit" class="btn btn-primary btn-block">Entrar</button>
					
					<?php if($this->view->login == 'erro') { ?>

		                <small class="form-text text-danger">
		                    Login ou senha incorretos.
		                </small>

		            <?php } ?>

				</form>

		    </div>

	  	</div>
	  </div>
	</div>
  </div>  
</div>