        <div class="container mx-3">
          
          <div class="row mb-3">
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Cooperativas Administradas
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="numerovendas">?</h5>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Número de PAs
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="totalvendas">?</h5>
                </div>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Usuários Cooperativas
                </div>
                <div class="card-body">
                  <h5 class="card-title">?</h5>
                </div>
              </div>
            </div>

          </div>
          
          <div class="row mb-3">
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Computadores gerenciados
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="numerovendas">?</h5>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Servidores gerenciados
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="totalvendas">?</h5>
                </div>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Firewalls gerenciados
                </div>
                <div class="card-body">
                  <h5 class="card-title">?</h5>
                </div>
              </div>
            </div>

          </div>
          
          <div class="row mb-3">
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Equipe Infra-Credis
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="numerovendas">?</h5>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Relatório Emitidos
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="totalvendas">?</h5>
                </div>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Visitas Realizadas
                </div>
                <div class="card-body">
                  <h5 class="card-title">?</h5>
                </div>
              </div>
            </div>

          </div>

			  </div>