<?php if($_SESSION['permissao'] == 'Administrador') {

    
	if(isset($this->view->cooperativas['mensagem'])) {
        $mensagem = $this->view->cooperativas['mensagem'];
        switch ($mensagem) {
            case "duplicado":
                echo '<script>alert("Cooperativa já cadastrada!")</script>';
                break;
            case "erro":
                echo '<script>alert("Erro no preenchimento dos campos")</script>';
                break;
        }
    } ?>

     <main>
         <div class="container-fluid">
             <h1 class="mt-5 pt-3 my-1 panel-title">Gerenciar Cooperativa</h1>

            
            <?php if($_GET['acao'] == 'alterar') {?>  

                <form action="/alterar_cooperativa?acao=alterar" method="POST">
                    <input type="hidden" id="inputId" name="codigo_coop" value="<?= $this->view->cooperativas['codigo_coop']?>">

            <?php } elseif($_GET['acao'] == 'deletar') { ?>                                

                <form action="/alterar_cooperativa?acao=deletar" method="POST">
                    <input type="hidden" id="inputId" name="codigo_coop" value="<?= $this->view->cooperativas['codigo_coop']?>">

            <?php } else { ?>                                
                <form action="/alterar_cooperativa" method="POST">
            <?php }?>

            <?php 
            echo "<pre>";
            print_r($this->view->cooperativas);
            echo "</pre>";
            ?>

                <div class="form-row">
                    <div class="form-group col-md-2">
                        <label for="inputCodigo">Código</label>
                        <input type="text"  maxlength="4" class="form-control" id="inputCodigo" placeholder="Codigo da Cooperativa" name="codigo_coop" value="<?= $this->view->cooperativas['codigo_coop'] ?>">
                    </div>
                    <div class="form-group col-md-9">
                        <label for="inputNome">Nome</label>
                        <input type="text" class="form-control" id="inputNome" placeholder="Nome da Cooperativa" name="nome" value="<?= $this->view->cooperativas['nome'] ?>">
                    </div>
                    <div class="form-group col-md-1">
                        <label for="inputIC">Infra-Credis</label>
                        <select id="inputIC" class="form-control" name="infracredis">
                            
                            <?php if(isset($this->view->cooperativas['infracredis'])) { ?>
                                <option selected value="<?=$this->view->cooperativas['infracredis'] ?>"><?=$this->view->cooperativas['infracredis'] ?></option>
                            <?php } else {?>
                                <option selected>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-</option>                               
                            <?php }?>

                            <option value="Sim">Sim</option>
                            <option value="Não">Não</option>
                         </select>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-8">
                        <label for="inputCidade">Cidade</label>
                        <input type="text" class="form-control" id="inputCidade" placeholder="Cidade da Cooperativa" name="cidade_coop" value="<?= $this->view->cooperativas['cidade_coop'] ?>">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputEquipamentos">Equipamentos</label>
                        <input type="number" class="form-control" id="inputEquipamentos" name="qtd_equip" value="<?= $this->view->cooperativas['qtd_equip'] ?>">
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputAdesao">Data de Adesao</label>
                        <input type="date" class="form-control" id="inputAdesao" name="adesao" value="<?= $this->view->cooperativas['adesao'] ?>">
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6 border border-light rounded">
                        <div class="form-group">
                            <label for="inputDiretor">Diretoria</label>
                            <input type="text" class="form-control" id="inputDiretorRiscos" placeholder="Diretor de Riscos" name="diretoria[0]" value="<?= $this->view->cooperativas['diretoria'][0] ?>">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="inputDiretor2" placeholder="Diretor Executivo" name="diretoria[1]" value="<?= $this->view->cooperativas['diretoria'][1] ?>">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="inputDiretor3" placeholder="Diretor Executivo" name="diretoria[2]" value="<?= $this->view->cooperativas['diretoria'][2] ?>">
                        </div>
                    </div>
                    <div class="form-group col-md-6 border border-light rounded">
                        <div class="form-group">
                            <label for="inputTI">Equipe de TI</label>
                            <input type="text" class="form-control" id="inputTI" placeholder="Responsável de TI" name="resp_ti[0]" value="<?= $this->view->cooperativas['resp_ti'][0] ?>">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="inputTI" placeholder="Equipe de TI 2" name="resp_ti[1]" value="<?= $this->view->cooperativas['resp_ti'][1] ?>">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" id="inputTI" placeholder="Equipe de TI 3" name="resp_ti[2]" value="<?= $this->view->cooperativas['resp_ti'][2] ?>">
                        </div>
                    </div>
                </div>
                <?php if($_GET['acao'] == 'alterar') {?>  
                    <button type="submit" value="submit" class="btn btn-primary">Alterar</button>
                <?php } elseif($_GET['acao'] == 'deletar') {?>  
                    <button type="submit" value="submit" class="btn btn-danger">Deletar</button>
                <?php } else { ?>                                
                    <button type="submit" value="submit" class="btn btn-primary">Enviar</button>
                <?php }?>
            </form>
            <a href="/cooperativas" class="btn btn-warning">Voltar&nbsp;</a>
         </div>
     </main>
<?php } ?>