<?php if($_SESSION['permissao'] == 'Administrador') {

    
	if(isset($this->view->cooperativas['mensagem'])) {
        $mensagem = $this->view->cooperativas['mensagem'];
        switch ($mensagem) {
            case "duplicado":
                echo '<script>alert("Cooperativa já cadastrada!")</script>';
                break;
            case "erro":
                echo '<script>alert("Erro no preenchimento dos campos")</script>';
                break;
        }
    } ?>

     <main>
         <div class="container-fluid">
             <h1 class="mt-5 pt-3 my-1 panel-title">Gerenciar Cooperativa</h1>

            <?php echo $_GET['id'];?>
            <?php if($_GET['acao'] == 'alterar') {?>  

                <form action="/alterar_usuario?acao=alterar" method="POST">
                    <input type="hidden" id="inputId" name="codigo_coop" value="<?= $this->view->cooperativas['codigo_coop']?>">

            <?php } elseif($_GET['acao'] == 'deletar') { ?>                                

                <form action="/alterar_usuario?acao=deletar" method="POST">
                    <input type="hidden" id="inputId" name="codigo_coop" value="<?= $this->view->cooperativas['codigo_coop']?>">

            <?php } else { ?>                                
                <form action="/alterar_usuario" method="POST">
            <?php }?>

                <div class="form-group">
                     <label for="inputNome">Nome</label>
                     <input type="text" class="form-control" id="inputNome" placeholder="Nome da Cooperativa" name="nome" value="<?= $this->view->cooperativas['nome'] ?>">
                 </div>
                <div class="form-group">
                     <label for="inputNome">Nome</label>
                     <input type="text" class="form-control" id="inputNome" placeholder="Nome da Cooperativa" name="nome" value="<?= $this->view->cooperativas['nome'] ?>">
                 </div>
                 <div class="form-group">
                     <label for="inputEmail">Email</label>
                     <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email" value="<?= $this->view->cooperativas['email'] ?>">
                 </div>
                 <div class="form-row">
                     <div class="form-group col-md-6">
                     <label for="inputLogin">Login</label>
                     <input type="text" class="form-control" id="inputLogin" placeholder="Login do Usuário" name="login" value="<?= $this->view->cooperativas['login'] ?>">
                     </div>
                     <div class="form-group col-md-6">
                     <label for="inputSenha">Senha</label>
                     <input type="password" class="form-control" id="inputSenha" placeholder="Senha" name="senha" value="<?= $this->view->cooperativas['senha'] ?>">
                     </div>
                 </div>
                 <div class="form-row">
                     <div class="form-group col-md-4">
                         <label for="inputCooperativa">Cooperativa</label>
                         <select id="inputCooperativa" class="form-control" name="cooperativa">
                            
                            <?php if(isset($this->view->cooperativas['cooperativa'])) { ?>
                                <option selected value="<?=$this->view->cooperativas['cooperativa'] ?>"><?=$this->view->cooperativas['cooperativa'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <?php foreach($this->view->cooperativas as $idx_codigoCooperativa => $codigoCooperativa) {
                                  $codigo = $codigoCooperativa['codigo_coop']; 
                            ?>
                                <option value="<?=$codigo; ?>"><?=$codigo; ?></option>
                            <?php }?>
                         </select>
                     </div>
                     <div class="form-group col-md-4">
                         <label for="inputEquipe">Equipe</label>
                         <select id="inputEquipe" class="form-control" name="equipe">
                            
                            <?php if(isset($this->view->cooperativas['equipe'])) { ?>
                                <option selected value="<?=$this->view->cooperativas['equipe'] ?>"><?=$this->view->cooperativas['equipe'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <option value="Infraestrutura">Infraestrutura</option>
                            <option value="Infra-Credis">Infra-Credis</option>
                            <option value="Cooperativa">Cooperativa</option>
                         </select>
                     </div>
                     <div class="form-group col-md-4">
                         <label for="inputPermissao">Permissão</label>
                         <select id="inputPermissao" class="form-control" name="permissao">
                            
                            <?php if(isset($this->view->cooperativas['permissao'])) { ?>
                                <option selected value="<?=$this->view->cooperativas['permissao'] ?>"><?=$this->view->cooperativas['permissao'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <option value="Administrador">Administrador</option>
                            <option value="Edição">Edição</option>
                            <option value="Visualização">Visualização</option>
                            <option value="Cooperativas">Cooperativas</option>
                         </select>
                     </div>
                </div>
                <?php if($_GET['acao'] == 'alterar') {?>  
                    <button type="submit" value="submit" class="btn btn-primary">Alterar</button>
                <?php } elseif($_GET['acao'] == 'deletar') {?>  
                    <button type="submit" value="submit" class="btn btn-danger">Deletar</button>
                <?php } else { ?>                                
                    <button type="submit" value="submit" class="btn btn-primary">Enviar</button>
                <?php }?>
            </form>
            <a href="/cooperativas" class="btn btn-warning">Voltar&nbsp;</a>
         </div>
     </main>
<?php } ?>