<?php if($_SESSION['permissao'] == 'admin' || $_SESSION['permissao'] == 'edit') { ?>
    <main>
        <div class="container-fluid">
            <h1 class="mt-5 pt-3 my-1 panel-title">Dashboard SAIC</h1>
            <hr><br>

            <div class="row justify-content-center"> 
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Cooperativas Administradas</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalCoops"];?></span>&nbsp;Cooperativas
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Número de PAs</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalPas"];?></span>&nbsp;PAs
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Usuários - Cooperativas</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalUsuarios"];?></span>&nbsp;Usuários
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center"> 
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Computadores Gerenciados</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalEquip"];?></span>&nbsp;Computadores Gerenciados
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Servidores Gerenciados</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalServidores"];?></span>&nbsp;Servidores Gerenciados
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Firewalls Gerenciados</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalFirewalls"];?></span>&nbsp;Firewalls Gerenciados
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center"> 
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Equipe Infra-Credis</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalIc"];?></span>&nbsp;Profissionais Infra-Credis
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Relatórios Emitidos</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalRelatorios"];?></span>&nbsp;Relatórios Emitidos
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card text-white mb-4">
                        <div class="card-body bg-info">Visitas Realizadas</div>
                        <div class="card-footer d-flex text-secondary">
                            <span class="dashboard-"><?php echo $this->view->dashboard["totalVisitas"];?></span>&nbsp;Visitas Realizadas
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
<?php } ?>

<?php if($_SESSION['permissao'] == 'view') { ?>
    <main>
        <div class="container-fluid">
<h1 class="my-1 panel-title">SAIC</h1>
<hr><br>
        </div>
    </main>
<?php } ?>