<?php if($_SESSION['permissao'] == 'Administrador') {

    
	if(isset($this->view->pas['mensagem'])) {
        $mensagem = $this->view->pas['mensagem'];
        switch ($mensagem) {
            case "duplicado":
                echo '<script>alert("Ponto de Atendimento já cadastrado!")</script>';
                break;
            case "erro":
                echo '<script>alert("Erro no preenchimento dos campos")</script>';
                break;
        }
    } ?>

     <main>
         <div class="container-fluid">
             <h1 class="mt-5 pt-3 my-1 panel-title">Gerenciar Ponto de Atendimento</h1><hr>

            
            <?php if($_GET['acao'] == 'alterar') {?>  

                <form action="/pa_alterar?acao=alterar" method="POST">
                    <input type="hidden" id="inputId" name="id_pa" value="<?= $this->view->pas['id_pa']?>">

            <?php } elseif($_GET['acao'] == 'deletar') { ?>                                

                <form action="/pa_alterar?acao=deletar" method="POST">
                    <input type="hidden" id="inputId" name="id_pa" value="<?= $this->view->pas['id_pa']?>">

            <?php } else { ?>                                
                <form action="/pa_alterar" method="POST">
            <?php }?>

                <div class="form-row">
                
                    <div class="form-group col-md-2">
                        <label for="inputCoop">Cooperativa</label>
                        <select id="inputCoop" class="form-control" name="coop">
                            
                            <?php if(isset($this->view->pas['coop'])) { ?>
                                <option selected value="<?=$this->view->pas['coop'] ?>"><?=$this->view->pas['coop'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <?php foreach($this->view->cooperativas as $idx_codigoCooperativa => $codigoCooperativa) {
                                  $codigo = $codigoCooperativa['codigo_coop']; 
                            ?>
                                <option value="<?=$codigo; ?>"><?=$codigo; ?></option>
                            <?php }?>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label for="inputCodigo">Código PA</label>
                        <input type="text"  maxlength="2" class="form-control" id="inputPa" placeholder="Código PA" name="codigo_pa" value="<?= $this->view->pas['codigo_pa'] ?>">
                    </div>
                    <div class="form-group col-md-8">
                        <label for="inputCidade">Cidade</label>
                        <select id="inputCidade" class="form-control selectpicker" name="nome_cidade" data-live-search="true">
                            
                            <?php if(isset($this->view->pas['nome_cidade'])) { ?>
                                <option selected value="<?=$this->view->pas['nome_cidade'] ?>"><?=$this->view->pas['nome_cidade'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }
                            
                            foreach($this->view->pas['cidades'] as $idx_cidades => $cidades)  { 
                                
                                if($cidades['nome_cidade'] != $this->view->pas['nome_cidade']) { ?>
                                <option value="<?=$cidades['nome_cidade']; ?>"><?=$cidades['nome_cidade']; ?></option>
                            <?php 
                                }
                            }
                            ?>
                         </select>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label for="inputTipoPA">Tipo de PA</label>
                        <select id="inputTipoPA" class="form-control" name="tipo_pa">
                            
                            <?php if(isset($this->view->pas['tipo_pa'])) { ?>
                                <option selected value="<?=$this->view->pas['tipo_pa'] ?>"><?=$this->view->pas['tipo_pa'] ?></option>
                            <?php } else {?>
                                <option selected>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-</option>                               
                            <?php } ?>
                            
                                <option value="Matriz">Matriz</option>                            
                                <option value="CAD">CAD</option>                            
                                <option value="Contingência">Contingência</option>                            
                                <option value="Comum">Comum</option>

                         </select>
                    </div>
                    <div class="form-group col-md-8">
                        <label for="inputFirewall">Modelo de Firewall</label>
                        <select id="inputFirewall" class="form-control" name="firewall">
                            
                            <?php if(isset($this->view->pas['firewall'])) { ?>
                                <option selected value="<?=$this->view->pas['firewall'] ?>"><?=$this->view->pas['firewall'] ?></option>
                            <?php } else {?>
                                <option selected>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-</option>                               
                            <?php } ?>

                            <?php foreach($this->view->pas['firewalls'] as $idx_firewalls => $firewalls) {
                                $firewall = $firewalls['nome']; 
                            ?>
                                <option value="<?=$firewall; ?>"><?=$firewall; ?></option>
                            <?php } ?>
                            
                         </select>
                    </div>
                </div>
                
                <div class="row">
                    <div class="col-md-1">Interface</div>
                    <div class="col-md-5">Endereço IP</div>
                    <div class="col-md-2">Tecnologia</div>
                    <div class="col-md-2">Velocidade</div>
                    <div class="col-md-2">Provedor</div>
                    <hr>
                </div>

                <!---------------------------->
                
                <?php for($i=0; $i <= 5; $i++) { ?>

                    <div class="form-row">    
                        <div class="form-group col-md-1">X<?=$i?></div>		
                        <div class="form-group col-md-5">
                            <?php $idx = "link_x" . $i; ?>
                            <input type="text" maxlength="15" class="form-control" id=" inputIP x<?=$i?>_ip" placeholder="" name="link_x<?=$i?>['ip']" value="<?= $this->view->pas[$idx]['ip'] ?>">
                        </div>
                        <div class="form-group col-md-2">
                            <select id="inputTipoLink" class="form-control" name="link_x<?=$i?>['tecnologia']">
                                
                                <?php if(isset($this->view->pas[$idx]['tecnologia'])) { ?>
                                    <option selected value="<?=$this->view->pas[$idx]['tecnologia'] ?>"><?=$this->view->pas[$idx]['tecnologia'] ?></option>
                                <?php } else {?>
                                    <option selected disabled>Tecnologia</option>
                                <?php } ?>
                                
                                    <option value="MPLS">MPLS</option>                            
                                    <option value="Fibra">Fibra</option>                            
                                    <option value="ADSL ">ADSL </option>                            
                                    <option value="Rádio">Rádio</option>

                            </select>
                        </div>		
                        <div class="form-group col-md-2">	
                            <input type="text" maxlength="15" class="form-control" id=" inputIP x<?=$i?>_velocidade" placeholder="" name="link_x<?=$i?>['velocidade']" value="<?= $this->view->pas[$idx]['velocidade'] ?>">
                        </div>		
                        <div class="form-group col-md-2">	
                            <input type="text" maxlength="40" class="form-control" id=" inputIP x<?=$i?>_provedor" placeholder="" name="link_x<?=$i?>['provedor']" value="<?= $this->view->pas[$idx]['provedor'] ?>">
                        </div>
                    </div>
                <?php } ?>	

                <?php if($_GET['acao'] == 'alterar') {?>  
                    <button type="submit" value="submit" class="btn btn-primary">Alterar</button>
                <?php } elseif($_GET['acao'] == 'deletar') {?>  
                    <button type="submit" value="submit" class="btn btn-danger">Deletar</button>
                <?php } else { ?>                                
                    <button type="submit" value="submit" class="btn btn-primary">Enviar</button>
                <?php }?>
            </form>
            <a href="/pas" class="btn btn-warning">Voltar&nbsp;</a>
         </div>
     </main>
<?php } ?>