<?php if($_SESSION['permissao'] == 'Administrador') { 
    
	if(isset($_GET['mensagem'])) {
        $mensagem = $_GET['mensagem'];
        switch ($mensagem) {
            case "sucesso":
                echo '<script>alert("Ponto de Atendimento cadastrado com sucesso!")</script>';
                break;
            case "alterado":
                echo '<script>alert("Ponto de Atendimento alterado!")</script>';
                break;
            case "deletado":
                echo '<script>alert("Ponto de Atendimento deletado com sucesso!")</script>';
                break;
        }
    }

    
?>
    <main>
        <div class="container-fluid">
            <h1 class="mt-5 pt-3 my-1 panel-title">Gerenciar Pontos de Atendimento</h1>
            <hr><br>
            <button type="button" class="btn btn-info btn-sm mb-4">
                <a class="nav-link text-white" href="/pas-adicionar" id="adiciona-pas">
                    <i class="side-icon">
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="plus-square" class="svg-inline--fa fa-plus-square fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M400 32H48C21.5 32 0 53.5 0 80v352c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48V80c0-26.5-21.5-48-48-48zm-32 252c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92H92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z"></path></svg>
                    </i>
                                Adicionar Ponto de Atendimento
                </a>
            </button>
            <div class="card mb-4">
                <div class="card-header">
                    <i class="mr-1">
                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user-friends" class="side-icon svg-inline--fa fa-user-friends fa-w-20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path fill="currentColor" d="M192 256c61.9 0 112-50.1 112-112S253.9 32 192 32 80 82.1 80 144s50.1 112 112 112zm76.8 32h-8.3c-20.8 10-43.9 16-68.5 16s-47.6-6-68.5-16h-8.3C51.6 288 0 339.6 0 403.2V432c0 26.5 21.5 48 48 48h288c26.5 0 48-21.5 48-48v-28.8c0-63.6-51.6-115.2-115.2-115.2zM480 256c53 0 96-43 96-96s-43-96-96-96-96 43-96 96 43 96 96 96zm48 32h-3.8c-13.9 4.8-28.6 8-44.2 8s-30.3-3.2-44.2-8H432c-20.4 0-39.2 5.9-55.7 15.4 24.4 26.3 39.7 61.2 39.7 99.8v38.4c0 2.2-.5 4.3-.6 6.4H592c26.5 0 48-21.5 48-48 0-61.9-50.1-112-112-112z"></path></svg>
                    </i>
                                Lista de Pontos de Atendimento
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Cooperativa</th>
                                    <th>Código</th>
                                    <th>Cidade</th>
                                    <th>Tipo de PA</th>
                                    <th>Modelo Firewall</th>
                                    <th>X0</th>
                                    <th>X1</th>
                                    <th>X2</th>
                                    <th>X3</th>
                                    <th>X4</th>
                                    <th>X5</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody style="font-size: 13px">
                                <?php foreach($this->view->pas as $idx_pa => $pa) {?>
                                    <tr>
                                        <td><?=$pa['coop']; ?></td>
                                        <td><?=$pa['codigo_pa']; ?></td>
                                        <td><?=$pa['nome_cidade']; ?></td>
                                        <td><?=$pa['tipo_pa']; ?></td>
                                        <td><?=$pa['firewall']; ?></td>
                                        
                                        <?php
                                            for($i=0; $i <= 5; $i++) { 
                                                $idx1 = "link_x".$i;?>
                                            <td>    
                                                <?= $pa[$idx1]['ip']?>
                                            </td>                                            
                                        <?php } ?>

                                        <td>
                                            <div class="">
                                                <a href="/pas-adicionar?acao=alterar&id=<?=$pa['id_pa']; ?>">
                                                    <i data-toggle="tooltip" data-placement="top" title="Editar PA">                                                    
                                                        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="map-marker-alt" class="mr-3 svg-inline--fa fa-map-marker-alt fa-w-12" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><path fill="currentColor" d="M172.268 501.67C26.97 291.031 0 269.413 0 192 0 85.961 85.961 0 192 0s192 85.961 192 192c0 77.413-26.97 99.031-172.268 309.67-9.535 13.774-29.93 13.773-39.464 0zM192 272c44.183 0 80-35.817 80-80s-35.817-80-80-80-80 35.817-80 80 35.817 80 80 80z"></path></svg>
                                                    </i>
                                                </a>
                                                <a href="/pas-adicionar?acao=deletar&id=<?=$pa['id_pa']; ?>">
                                                    <i data-toggle="tooltip" data-placement="top" title="Excluir PA"> 
                                                        <svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="trash-alt" class="mr-3 svg-inline--fa fa-trash-alt fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M268 416h24a12 12 0 0 0 12-12V188a12 12 0 0 0-12-12h-24a12 12 0 0 0-12 12v216a12 12 0 0 0 12 12zM432 80h-82.41l-34-56.7A48 48 0 0 0 274.41 0H173.59a48 48 0 0 0-41.16 23.3L98.41 80H16A16 16 0 0 0 0 96v16a16 16 0 0 0 16 16h16v336a48 48 0 0 0 48 48h288a48 48 0 0 0 48-48V128h16a16 16 0 0 0 16-16V96a16 16 0 0 0-16-16zM171.84 50.91A6 6 0 0 1 177 48h94a6 6 0 0 1 5.15 2.91L293.61 80H154.39zM368 464H80V128h288zm-212-48h24a12 12 0 0 0 12-12V188a12 12 0 0 0-12-12h-24a12 12 0 0 0-12 12v216a12 12 0 0 0 12 12z"></path></svg>
                                                    </i>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>
<?php } ?>