<?php 

   if(isset($_GET['mensagem'])) {
        $mensagem = $_GET['mensagem'];
        switch ($mensagem) {
            case "senhaincorreta":
                echo '<script>alert("A senha atual está incorreta!")</script>';
                break;
                case "naoconfere":
                    echo '<script>alert("Os campos novas senhas não conferem!")</script>';
                    break;
                case "sucesso":
                    echo '<script>alert("Senha alterada com sucesso!")</script>';
                    break;
        }
    }

?>

 <main>
    <div class="container-fluid">
        <h1 class="mt-5 pt-3 my-1 panel-title">Resetar senha</h1>
                        <p class=" ml-3">Usuário: <?php echo $_SESSION['nome']?><p><hr>
        <form action="/senha_alterar" method="POST">
                <div class="form-group col-md-4">
                    <label for="inputSenha">Senha Atual</label>
                    <input type="password" class="form-control mb-2" id="inputSenha" placeholder="Senha Atual" name="senha" value="">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputSenhaNova1">Senha Nova</label>
                    <input type="password" class="form-control mb-2" id="inputSenhaNova1" placeholder="Insira a senha" name="senha_nova1" value="">
                    <input type="password" class="form-control mb-3" id="inputSenhaNova2" placeholder="Repita a senha" name="senha_nova2" value="">
                </div>       
            <button type="submit" value="submit" class="btn btn-primary ml-3">Alterar</button>
        </form>
        <a href="/main" class="btn btn-warning ml-3">Voltar&nbsp;</a>
    </div>
</main>