<main>
    <div class="container-fluid">
        <h1 class="mt-5 pt-3 my-1 panel-title">Resetar senha</h1>
        <form action="/senha_alterar" method="POST">
            <div class="form-row">
                <div class="form-group col-md-6">
                        <label for="inputUsuario">Usuário: <?php echo $_SESSION['nome']?></label>
                    </div>
                    <div class="form-group col-md-6">
                        <input type="id_usuario" class="form-control" id="inputid_usuario" name="id_usuario" value="<?= $this->view->usuarios['id_usuario'] ?>">
                    </div>
                    <div class="form-row col-md-6">
                        <label for="inputSenhaAntiga">Senha Antiga</label>
                        <input type="password" class="form-control" id="inputSenhaAntiga" placeholder="Senha Antiga" name="senha_antiga" value="">
                    </div>
                    <div class="form-row col-md-6">
                        <label for="inputSenhaNova1">Senha Nova1</label>
                        <input type="password" class="form-control" id="inputSenhaNova1" placeholder="Senha Nova1" name="senha_nova1" value="">
                        <input type="password" class="form-control" id="inputSenhaNova2" placeholder="Senha Nova2" name="senha_nova2" value="">
                    </div>
                </div>
            </div>        
            <button type="submit" value="submit" class="btn btn-primary">Alterar</button>
           
       </form>
       <a href="/main" class="btn btn-warning">Voltar&nbsp;</a>
    </div>
</main>