<?php if($_SESSION['permissao'] == 'Administrador') {

    
	if(isset($this->view->usuarios['mensagem'])) {
        $mensagem = $this->view->usuarios['mensagem'];
        switch ($mensagem) {
            case "duplicado":
                echo '<script>alert("Usuário já cadastrado!")</script>';
                break;
            case "erro":
                echo '<script>alert("Erro no preenchimento dos campos")</script>';
                break;
        }
    } ?>

     <main>
         <div class="container-fluid">
             <h1 class="mt-5 pt-3 my-1 panel-title">Gerenciar Usuario</h1>

            <?php if($_GET['acao'] == 'alterar') {?>  

                <form action="/usuario_alterar?acao=alterar" method="POST">
                    <input type="hidden" id="inputId" name="id_usuario" value="<?= $this->view->usuarios['id_usuario']?>">

            <?php } elseif($_GET['acao'] == 'deletar') { ?>                                

                <form action="/usuario_alterar?acao=deletar" method="POST">
                    <input type="hidden" id="inputId" name="id_usuario" value="<?= $this->view->usuarios['id_usuario']?>">

            <?php } else { ?>                                
                <form action="/usuario_alterar" method="POST">
            <?php }?>

                <div class="form-group">
                     <label for="inputNome">Nome</label>
                     <input type="text" class="form-control" id="inputNome" placeholder="Nome Completo do usuário" name="nome" value="<?= $this->view->usuarios['nome'] ?>">
                 </div>
                 <div class="form-group">
                     <label for="inputEmail">Email</label>
                     <input type="email" class="form-control" id="inputEmail" placeholder="Email" name="email" value="<?= $this->view->usuarios['email'] ?>">
                 </div>
                 <div class="form-row">
                     <div class="form-group col-md-6">
                     <label for="inputLogin">Login</label>
                     <input type="text" class="form-control" id="inputLogin" placeholder="Login do Usuário" name="login" value="<?= $this->view->usuarios['login'] ?>">
                     </div>
                     <div class="form-group col-md-6">
                     <label for="inputSenha">Senha</label>
                     <input type="password" class="form-control" id="inputSenha" placeholder="*******" name="senha" value="">
                     </div>
                 </div>
                 <div class="form-row">
                     <div class="form-group col-md-4">
                         <label for="inputCooperativa">Cooperativa</label>
                         <select id="inputCooperativa" class="form-control" name="cooperativa">
                            
                            <?php if(isset($this->view->usuarios['cooperativa'])) { ?>
                                <option selected value="<?=$this->view->usuarios['cooperativa'] ?>"><?=$this->view->usuarios['cooperativa'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <?php foreach($this->view->cooperativas as $idx_codigoCooperativa => $codigoCooperativa) {
                                  $codigo = $codigoCooperativa['codigo_coop']; 
                            ?>
                                <option value="<?=$codigo; ?>"><?=$codigo; ?></option>
                            <?php }?>
                         </select>
                     </div>
                     <div class="form-group col-md-4">
                         <label for="inputEquipe">Equipe</label>
                         <select id="inputEquipe" class="form-control" name="equipe">
                            
                            <?php if(isset($this->view->usuarios['equipe'])) { ?>
                                <option selected value="<?=$this->view->usuarios['equipe'] ?>"><?=$this->view->usuarios['equipe'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <option value="Infraestrutura">Infraestrutura</option>
                            <option value="Infra-Credis">Infra-Credis</option>
                            <option value="Cooperativa">Cooperativa</option>
                         </select>
                     </div>
                     <div class="form-group col-md-4">
                         <label for="inputPermissao">Permissão</label>
                         <select id="inputPermissao" class="form-control" name="permissao">
                            
                            <?php if(isset($this->view->usuarios['permissao'])) { ?>
                                <option selected value="<?=$this->view->usuarios['permissao'] ?>"><?=$this->view->usuarios['permissao'] ?></option>
                            <?php } else {?>
                                <option selected>Selecione...</option>                               
                            <?php }?>

                            <option value="Administrador">Administrador</option>
                            <option value="Edição">Edição</option>
                            <option value="Visualização">Visualização</option>
                            <option value="Cooperativas">Cooperativas</option>
                         </select>
                     </div>
                </div>
                <?php if($_GET['acao'] == 'alterar') {?>  
                    <button type="submit" value="submit" class="btn btn-primary">Alterar</button>
                <?php } elseif($_GET['acao'] == 'deletar') {?>  
                    <button type="submit" value="submit" class="btn btn-danger">Deletar</button>
                <?php } else { ?>                                
                    <button type="submit" value="submit" class="btn btn-primary">Enviar</button>
                <?php }?>
            </form>
            <a href="/usuarios" class="btn btn-warning">Voltar&nbsp;</a>
         </div>
     </main>
<?php } ?>