<nav class="navbar navbar-dark sticky-top bg-dark p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">IC-DOC</a>
  <ul class="navbar-nav mr-auto d-flex flex-row">
    <li class="nav-item px-4"><a class="nav-link" href="/main">Documentação</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/implantacao">Implantação</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/monitoramento">Monitoramento</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/rateio">Rateio</a></li>
  </ul>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Logout</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <i class="fas fa-tachometer-alt px-2"></i>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-users-cog px-2"></i>
              Gestão de Usuários <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-list px-2"></i>
              Consultar Itens <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-file-invoice px-2"></i>
              Documentação <span class="sr-only"></span>
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Cadastrar Itens</span>
        </h6>

        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="far fa-building px-2"></i>
              Cooperativa <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-map-marker-alt px-2"></i>
              Ponto de Atendimento <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-server px-2"></i>
              Servidores <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-network-wired px-2"></i>
              Serviços de Rede <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-shield-alt px-2"></i>
              Sistemas de Segurança <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-undo-alt px-2"></i>
              Rotinas de Backup <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-cogs px-2"></i>
              Outras Aplicações <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <i class="fas fa-cogs px-2"></i>
              Relatório de Avaliação <span class="sr-only"></span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="main" id="pagina">
		    
		    <div class="container">
          
          <div class="row mb-3">
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Cooperativas Administradas
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="numerovendas">?</h5>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Número de PAs
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="totalvendas">?</h5>
                </div>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Usuários Cooperativas
                </div>
                <div class="card-body">
                  <h5 class="card-title">?</h5>
                </div>
              </div>
            </div>

          </div>
          
          <div class="row mb-3">
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Computadores gerenciados
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="numerovendas">?</h5>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Servidores gerenciados
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="totalvendas">?</h5>
                </div>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Firewalls gerenciados
                </div>
                <div class="card-body">
                  <h5 class="card-title">?</h5>
                </div>
              </div>
            </div>

          </div>
          
          <div class="row mb-3">
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Equipe Infra-Credis
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="numerovendas">?</h5>
                </div>
              </div>
            </div>

            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Visitas realizadas
                </div>
                <div class="card-body">
                  <h5 class="card-title" id="totalvendas">?</h5>
                </div>
              </div>
            </div>
          
            <div class="col-md-4">
              <div class="card">
                <div class="card-header">
                  Relatórios Emitidos
                </div>
                <div class="card-body">
                  <h5 class="card-title">?</h5>
                </div>
              </div>
            </div>

          </div>

				
		    </div>

		</div>