<nav class="navbar navbar-dark sticky-top bg-dark p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">IC-DOC</a>
  <ul class="navbar-nav mr-auto d-flex flex-row">
    <li class="nav-item px-4"><a class="nav-link" href="/main">Documentação</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/implantacao">Implantação</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/monitoramento">Monitoramento</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/rateio">Rateio</a></li>
  </ul>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Logout</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item side-item">
            <a class="nav-link active" href="#">
              <img class="side-icon" src="icons/dashboard-icon.svg">
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/users-icon.svg">
              Gestão de Usuários <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/list-icon.svg">
              Consultar Itens <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/doc-icon.svg">
              Documentação <span class="sr-only"></span>
            </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Cadastrar Itens</span>
        </h6>

        <ul class="nav flex-column">
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/coop-icon.svg">
              Cooperativa <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/pa-icon.svg">
              Ponto de Atendimento <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/server-icon.svg">
              Servidores <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/network-icon.svg">
              Serviços de Rede <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/security-icon.svg">
              Sistemas de Segurança <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/backup-icon.svg">
              Rotinas de Backup <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/apps-icon.svg">
              Outras Aplicações <span class="sr-only"></span>
            </a>
          </li>
          <li class="nav-item side-item">
            <a class="nav-link" href="#">
              <img class="side-icon" src="icons/report-icon.svg">
              Relatório de Avaliação <span class="sr-only"></span>
            </a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="main" id="pagina">
		    
		    <?php 
          
          include 'screens/dashboard.phtml';
        
        ?>

		</div>