                <main>
                    <div class="container-fluid">
                        <h1 class="my-1 panel-title">Dashboard SAIC</h1>
                        <hr><br>                        
                        <div class="seleciona-coop border border-muted rounded  mb-4">                            
                            <div class="col align-self-start  align-self-center">                            
                                <form class="mx-2">
                                    <div class="form-group row" data-style="btn-info">
                                        <label class="col-sm-9 col-form-label">Visão dos dados da Cooperativa:</label>
                                        <div class="col-sm-3">
                                            <select class="form-control-plaintext" id="competencia" >
                                                <option class="text-secondary" value="1003">Geral</option>
                                                <option class="text-secondary" value="3456">3456</option>
                                                <option class="text-secondary" value="3210">3210</option>
                                            </select>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="row justify-content-center"> 
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Cooperativas Administradas</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Número de PAs</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Responsáveis TI - Cooperativas</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center"> 
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Computadores Gerenciados</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Servidores Gerenciados</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Firewalls Gerenciados</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center"> 
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Equipe Infra-Credis</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Relatório Emitidos</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Visitas Realizadas</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between text-secondary">
                                        ??????
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>