<?php if($_SESSION['permissao'] == 'admin' || $_SESSION['permissao'] == 'edit') { ?>
                <main>
                    <div class="container-fluid">
                        <h1 class="my-1 panel-title">Dashboard SAIC</h1>
                        <hr><br>                       
                        <div class="seleciona-coop border border-muted rounded  mb-4">                            
                            <div class="col align-self-start  align-self-center">                            
                                <form class="mx-2">
                                    <div class="form-group row" data-style="btn-info">
                                        <label class="col-sm-9 col-form-label">Visão dos dados da Cooperativa:</label>
                                        <div class="col-sm-3">
                                            <select class="form-control-plaintext" id="competencia" >
                                                <option class="text-secondary" value="1003">Geral</option>
                                                <option class="text-secondary" value="3456">3456</option>
                                                <option class="text-secondary" value="3210">3210</option>
                                            </select>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="row justify-content-center"> 
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Cooperativas Administradas</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">42</span>&nbsp;Cooperativas
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Número de PAs</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">250</span>&nbsp;PAs
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Responsáveis TI - Cooperativas</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">45</span>&nbsp;Profissionais de TI
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center"> 
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Computadores Gerenciados</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">3200</span>&nbsp;Computadores Gerenciados
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Servidores Gerenciados</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">92</span>&nbsp;Servidores Gerenciados
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Firewalls Gerenciados</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">300</span>&nbsp;Firewalls Gerenciados
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-center"> 
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Equipe Infra-Credis</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">8</span>&nbsp;Profissionais Infra-Credis
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Relatórios Emitidos</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">79</span>&nbsp;Relatórios Emitidos
                                    </div>
                                </div>
                            </div>
                            <div class="col">
                                <div class="card text-white mb-4">
                                    <div class="card-body bg-info">Visitas Realizadas</div>
                                    <div class="card-footer d-flex text-secondary">
                                        <span class="dashboard-">52</span>&nbsp;Visitas Realizadas
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
<?php } ?>

<?php if($_SESSION['permissao'] == 'view') { ?>
    <main>
        <div class="container-fluid">
            <h1 class="my-1 panel-title">SAIC</h1>
            <hr><br>
        </div>
    </main>
<?php } ?>