<nav class="navbar navbar-dark sticky-top bg-dark p-0">
        <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">IC-DOC</a>
  <ul class="navbar-nav mr-auto d-flex flex-row">
    <li class="nav-item px-4"><a class="nav-link" href="/main">Documentação</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/implantacao">Implantação</a></li>
    <li class="nav-item px-4"><a class="nav-link" href="/monitoramento">Monitoramento</a></li>

    <?php if($_SESSION['permissao'] == 'edit' || $_SESSION['permissao'] == 'admin') { ?>
    <li class="nav-item px-4"><a class="nav-link" href="/rateio">Rateio</a></li>
    <?php } ?>
    
  </ul>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="/logout">Logout</a>
    </li>
  </ul>
</nav>