<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" data-toggle="tooltip" data-placement="top" title="Sistema de Acompanhamento IC" href="/main">SAIC</a>
             
    <?php if($_SESSION['permissao'] == 'admin' || $_SESSION['permissao'] == 'edit') { ?>
        <div class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Administração
            </button>
            <div class="dropdown-menu">
                        
                <?php if($_SESSION['permissao'] == 'admin') { ?>
                <a class="alinha-menu dropdown-item lateral-captura-id" href="#" id="lateral-usuarios">
                            - Gestão de Usuários
                </a>                      
                <?php } ?>
                        
                <div class="dropdown-divider"></div>
                <a class="alinha-menu dropdown-item lateral-captura-id" href="#" id="lateral-cooperativa">
                            - Gerenciar Cooperativas
                </a></a>
            </div>
        </div>  
    <?php } ?>
             
    <div class="dropdown">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Documentação
        </button>
        <div class="dropdown-menu">
                        
            <?php if($_SESSION['permissao'] == 'admin' || $_SESSION['permissao'] == 'edit') { ?>
                <a class="alinha-menu dropdown-item lateral-captura-id" href="#" id="lateral-hwsw">- Cadastrar Item</a>
                <div class="dropdown-divider"></div>
            <?php } ?>

            <a class="alinha-menu dropdown-item" href="#">- Consultar Item</a>
            <a class="alinha-menu dropdown-item" href="#">- Consultar Documentação</a>
                    
        </div>
    </div>

    <div class="dropdown">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Implantação
        </button>
        <div class="dropdown-menu">
                        
            <?php if($_SESSION['permissao'] == 'admin' || $_SESSION['permissao'] == 'edit') { ?>
                <a class="alinha-menu dropdown-item" href="#">- Cadastrar Etapa</a>
                <a class="alinha-menu dropdown-item" href="#">- Alterar Etapa</a>
                <div class="dropdown-divider"></div>
            <?php } ?>
            <a class="alinha-menu dropdown-item" href="#">- Consultar Cooperativas</a>
                    
        </div>
    </div>

    <div class="dropdown">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Monitoramento
        </button>
        <div class="dropdown-menu">
                        
            <a class="alinha-menu dropdown-item" href="#">- Menu 1</a>
            <a class="alinha-menu dropdown-item" href="#">- Menu 2</a>
            <a class="alinha-menu dropdown-item" href="#">- Menu 3</a>
            <a class="alinha-menu dropdown-item" href="#">- Menu 4</a>
                    
        </div>
    </div>
             
    <?php if($_SESSION['permissao'] == 'admin' || $_SESSION['permissao'] == 'edit') { ?>
        <div class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Rateio
            </button>
            <div class="dropdown-menu">
                         
                <?php if($_SESSION['permissao'] == 'admin') { ?>
                    <a class="alinha-menu dropdown-item" href="#">- Calcular Rateio</a>
                <?php } ?>

                <div class="dropdown-divider"></div>
                <a class="alinha-menu dropdown-item" href="#">- Vizualizar Rateio</a>

            </div>
        </div>  
    <?php } ?>

    <ul class="navbar-nav d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i>
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user" class="svg-inline--fa fa-user fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M224 256c70.7 0 128-57.3 128-128S294.7 0 224 0 96 57.3 96 128s57.3 128 128 128zm89.6 32h-16.7c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16h-16.7C60.2 288 0 348.2 0 422.4V464c0 26.5 21.5 48 48 48h352c26.5 0 48-21.5 48-48v-41.6c0-74.2-60.2-134.4-134.4-134.4z"></path></svg></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <span class="alinha-menu dropdown-item" href="#">Usuário:<?php echo $_SESSION['nome']?></span>
                <span class="alinha-menu dropdown-item" href="#">Cooperativa:<?php echo $_SESSION['cooperativa']?></span>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/logout">Logout</a>
            </div>
        </li>
    </ul>
</nav>