<html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="System of IT assets Documentation" />
        <meta name="author" content="Fabiano Souza" />
        <title>SAIC</title>

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<link href="css/styles.css" rel="stylesheet" />
        <link href="css/dataTables.bootstrap4.css" rel="stylesheet"/>
		<script src="assets/all.js"></script>
		
		<!--script src="/js/script.js"></!--script-->

	</head>

	<body class="sb-nav-fixed">

		<?= $this->content() ?>
		
		<script src="assets/jquery-3.5.1.js" ></script>
		<script src="assets/bootstrap.bundle.js" ></script>
		<script src="js/scripts.js"></script>
		<script src="assets/Chart.js" ></script>
		<script src="assets/demo/chart-area-demo.js"></script>
		<script src="assets/demo/chart-bar-demo.js"></script>
		<script src="assets/jquery.dataTables.js" ></script>
		<script src="assets/dataTables.bootstrap4.js" ></script>
		<script src="assets/demo/datatables-demo.js"></script>
	  
	</body>

</html>